### ISSUE TITLE
Include code examples

### ISSUE THREAD

**Issue by kalepail** [Tangem/tangem-sdk-cordova#1]
Either in the README, the Wiki or an examples directory. This is an amazing combo of software/hardware but for developers to really "get it" they'll need a little more help to go off of to kickstart their own instances.

**Comment by lazutkin-andrey** [comment]
Thank you for your request! We've added code examples to the README. 
Also, we have demo projects both for [Capacitor](https://github.com/Tangem/tangem-sdk-cordova/tree/master/capacitor-demo) and [Cordova](https://github.com/Tangem/tangem-sdk-cordova/tree/master/cordova-demo) that can really help to kickstart a new project.
