### ISSUE TITLE
Complete demos

### ISSUE THREAD

**Issue by kalepail** [Tangem/tangem-sdk-cordova#2]
Demos should be more fully fleshed out. The cordova one doesn't even have a README atm and the capacitor one is using the `serve` command which will open the app in the browser which won't work with the signing cards so physical device usage should be enforced.

Building the tech is really only 35% of our job as engineers. Documentation and marketing is the other 65%.

**Comment by lazutkin-andrey** [comment]
Thank you for this request and sorry for a long response. We've been working on the new version of this plugin. And now it's available.
From now every demo project has sufficient documentation to run it.
